Repository AY1920S1-CS2103T-T13-4/main, pull requests merged in 2019-10, with the labels that each got.

#69 Implement basic undo&redo
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/ClearCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/VersionedMark.java
  src/main/java/seedu/mark/ui/FolderStructureTreeView.java
  src/test/java/seedu/mark/logic/LogicManagerTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AddFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/ClearCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
  src/test/java/seedu/mark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/mark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#77 Update all the bookmark examples
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/FindCommand.java
  src/main/java/seedu/mark/logic/parser/Prefix.java
  src/main/java/seedu/mark/model/bookmark/Name.java
  src/main/java/seedu/mark/model/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/mark/model/util/SampleDataUtil.java
  src/main/java/seedu/mark/storage/JsonAdaptedBookmark.java
  src/main/java/seedu/mark/ui/BookmarkCard.java
  src/test/data/JsonMarkStorageTest/invalidAndValidBookmarkMark.json
  src/test/data/JsonMarkStorageTest/invalidBookmarkMark.json
  src/test/data/JsonSerializableMarkTest/duplicateBookmarkMark.json
  src/test/data/JsonSerializableMarkTest/invalidBookmarkMark.json
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/mark/model/ModelManagerTest.java
  src/test/java/seedu/mark/model/bookmark/RemarkTest.java
  src/test/java/seedu/mark/model/predicates/IdentifiersContainKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/UrlContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/testutil/BookmarkBuilder.java
  src/test/java/seedu/mark/testutil/BookmarkUtil.java
Labels: PR: reviewed-approved

#74 Implement tab views
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/TabCommand.java
  src/main/java/seedu/mark/logic/commands/results/CommandResult.java
  src/main/java/seedu/mark/logic/commands/results/TabCommandResult.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/logic/parser/TabCommandParser.java
  src/main/java/seedu/mark/ui/BrowserPanel.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/java/seedu/mark/ui/OfflinePanel.java
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OfflinePanel.fxml
  src/test/java/seedu/mark/logic/commands/TabCommandTest.java
  src/test/java/seedu/mark/logic/parser/TabCommandParserTest.java
Labels: PR: reviewed-approved

#73 Add Reminder Class
  src/main/java/seedu/mark/model/reminder/Note.java
  src/main/java/seedu/mark/model/reminder/Reminder.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/model/reminder/NoteTest.java
  src/test/java/seedu/mark/model/reminder/ReminderTest.java
  src/test/java/seedu/mark/testutil/ReminderBuilder.java
  src/test/java/seedu/mark/testutil/TypicalReminders.java
Labels: PR: reviewed-approved

#99 Fix #98
  src/main/resources/view/MainWindow.fxml
Labels: PR: reviewed-approved

#75 Add basic export and import commands
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/ClearCommand.java
  src/main/java/seedu/mark/logic/commands/Command.java
  src/main/java/seedu/mark/logic/commands/DeleteCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/ExitCommand.java
  src/main/java/seedu/mark/logic/commands/ExportCommand.java
  src/main/java/seedu/mark/logic/commands/FindCommand.java
  src/main/java/seedu/mark/logic/commands/GotoCommand.java
  src/main/java/seedu/mark/logic/commands/HelpCommand.java
  src/main/java/seedu/mark/logic/commands/ImportCommand.java
  src/main/java/seedu/mark/logic/commands/ListCommand.java
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/TabCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
  src/main/java/seedu/mark/logic/parser/ExportCommandParser.java
  src/main/java/seedu/mark/logic/parser/ImportCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/test/java/seedu/mark/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AddFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/ClearCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
  src/test/java/seedu/mark/logic/commands/ExitCommandTest.java
  src/test/java/seedu/mark/logic/commands/ExportCommandTest.java
  src/test/java/seedu/mark/logic/commands/FindCommandTest.java
  src/test/java/seedu/mark/logic/commands/GotoCommandTest.java
  src/test/java/seedu/mark/logic/commands/HelpCommandTest.java
  src/test/java/seedu/mark/logic/commands/ImportCommandTest.java
  src/test/java/seedu/mark/logic/commands/ListCommandTest.java
  src/test/java/seedu/mark/logic/commands/MarkImporterTest.java
  src/test/java/seedu/mark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/mark/logic/commands/TabCommandTest.java
  src/test/java/seedu/mark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/mark/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/storage/StorageStub.java
Labels: PR: reviewed-approved

#103 Fix tab switch NPE
  src/main/java/seedu/mark/ui/MainWindow.java
Labels: PR: reviewed-approved

#109 Move FolderStructure display to Dashboard
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: PR: reviewed-approved

#113 Set bookmark folders to ROOT during import
  src/main/java/seedu/mark/logic/commands/ImportCommand.java
  src/test/java/seedu/mark/logic/commands/ImportCommandTest.java
Labels: PR: reviewed-approved

#111 Automatic tab switching and open bookmarks via GUI
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/TabCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/java/seedu/mark/ui/MainWindow.java
Labels: PR: unreviewed

#94 Implement basic annotation
  build.gradle
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/logic/parser/CacheToOfflineParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/annotation/AnnotationNote.java
  src/main/java/seedu/mark/model/annotation/Highlight.java
  src/main/java/seedu/mark/model/annotation/OfflineDocument.java
  src/main/java/seedu/mark/model/annotation/Paragraph.java
  src/main/java/seedu/mark/model/annotation/ParagraphContent.java
  src/main/java/seedu/mark/model/annotation/ParagraphIdentifier.java
  src/main/java/seedu/mark/model/annotation/PhantomParagraph.java
  src/main/java/seedu/mark/model/annotation/TrueParagraph.java
  src/main/java/seedu/mark/ui/AnnotationListPanel.java
  src/main/java/seedu/mark/ui/AnnotationParagraphCard.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/java/seedu/mark/ui/OfflinePanel.java
  src/main/resources/view/AnnotationListPanel.fxml
  src/main/resources/view/AnnotationParagraphCard.fxml
  src/main/resources/view/OfflinePanel.fxml
  src/main/resources/view/sample_cache.html
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/annotation/AnnotationNoteTest.java
  src/test/java/seedu/mark/model/annotation/OfflineDocumentTest.java
  src/test/java/seedu/mark/model/annotation/ParagraphIdentifierTest.java
Labels: PR: merged

#112 Add autotag
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AutotagCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/parser/AutotagCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/ReadOnlyMark.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/main/java/seedu/mark/model/autotag/BookmarkTagger.java
  src/main/java/seedu/mark/model/autotag/SelectiveBookmarkTagger.java
  src/main/java/seedu/mark/model/tag/Tag.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagCommandTest.java
  src/test/java/seedu/mark/logic/parser/AutotagCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/MarkTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/autotag/AutotagControllerTest.java
  src/test/java/seedu/mark/model/autotag/BookmarkTaggerTest.java
  src/test/java/seedu/mark/model/autotag/SelectiveBookmarkTaggerTest.java
  src/test/java/seedu/mark/model/tag/TagTest.java
Labels: PR: reviewed-approved

#119 Improve undo/redo
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/AddReminderCommand.java
  src/main/java/seedu/mark/logic/commands/AutotagCommand.java
  src/main/java/seedu/mark/logic/commands/ClearCommand.java
  src/main/java/seedu/mark/logic/commands/Command.java
  src/main/java/seedu/mark/logic/commands/DeleteCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/FindCommand.java
  src/main/java/seedu/mark/logic/commands/GotoCommand.java
  src/main/java/seedu/mark/logic/commands/ImportCommand.java
  src/main/java/seedu/mark/logic/commands/ListCommand.java
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/TabCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
  src/main/java/seedu/mark/logic/parser/AddFolderCommandParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/VersionedMark.java
  src/test/java/seedu/mark/logic/LogicManagerTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AddFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/AddReminderCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagCommandTest.java
  src/test/java/seedu/mark/logic/commands/ClearCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
  src/test/java/seedu/mark/logic/commands/ImportCommandTest.java
  src/test/java/seedu/mark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/mark/logic/commands/TabCommandTest.java
  src/test/java/seedu/mark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/mark/logic/commands/results/CommandResultTest.java
  src/test/java/seedu/mark/logic/commands/results/ExitCommandResultTest.java
  src/test/java/seedu/mark/logic/commands/results/HelpCommandResultTest.java
  src/test/java/seedu/mark/logic/commands/results/TabCommandResultTest.java
  src/test/java/seedu/mark/logic/parser/GotoCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/TabCommandParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#128 Update Storage component + add folders implementation to devguide
  docs/DeveloperGuide.adoc
  docs/diagrams/FolderSequenceDiagram.puml
  docs/diagrams/FolderStructureClassDiagram.puml
  docs/diagrams/FolderStructureState0.puml
  docs/diagrams/FolderStructureState1.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/FolderSequenceDiagram.png
  docs/images/FolderStructureClassDiagram.png
  docs/images/FolderStructureState0.png
  docs/images/FolderStructureState1.png
  docs/images/StorageClassDiagram.png
Labels: PR: reviewed-approved

#126 Update Logic component in DevGuide + Update undo/redo implementation
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/Testing.adoc
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/SaveMarkActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/SaveMarkActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: PR: reviewed-approved

#127 Update UI component in DevGuide + Add annotation feature
  docs/DeveloperGuide.adoc
  docs/diagrams/AddAnnotationSequenceDiagram.puml
  docs/diagrams/AnnotationActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiTabViewClassDiagram.puml
  docs/images/AddAnnotationSequenceDiagram.png
  docs/images/AnnotationActivityDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiTabViewClassDiagram.png
Labels: PR: reviewed-approved

#131 Fix some examples in UG
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#129 Update Model component + Introduction + add implementation of autotag to DevGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/AnnotationPackageClassDiagram.puml
  docs/diagrams/AutotagSequenceDiagram.puml
  docs/diagrams/AutotagState0.puml
  docs/diagrams/AutotagState1.puml
  docs/diagrams/AutotagState2.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AnnotationPackageClassDiagram.png
  docs/images/AutotagSequenceDiagram.png
  docs/images/AutotagState0.png
  docs/images/AutotagState1.png
  docs/images/AutotagState2.png
  docs/images/ModelClassDiagram.png
Labels: PR: reviewed-approved

#130 Update DG and edit UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ReminderAssociationDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ReminderAssociationDiagram.png
Labels: PR: reviewed-approved

#135 Fix typo
  docs/DeveloperGuide.adoc
  docs/diagrams/SaveMarkActivityDiagram.puml
  docs/images/SaveMarkActivityDiagram.png
Labels: PR: reviewed-approved

#136 Update Mark version number in MainApp
  src/main/java/seedu/mark/MainApp.java
Labels: PR: reviewed-approved

#121 Add offline and cache
  build.gradle
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/logic/commands/CacheCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/ImportCommand.java
  src/main/java/seedu/mark/logic/commands/OfflineCommand.java
  src/main/java/seedu/mark/logic/commands/results/OfflineCommandResult.java
  src/main/java/seedu/mark/logic/parser/AddCommandParser.java
  src/main/java/seedu/mark/logic/parser/CacheCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/logic/parser/OfflineCommandParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/annotation/OfflineDocument.java
  src/main/java/seedu/mark/model/autotag/BookmarkTagger.java
  src/main/java/seedu/mark/model/bookmark/Bookmark.java
  src/main/java/seedu/mark/model/bookmark/CachedCopy.java
  src/main/java/seedu/mark/model/util/SampleDataUtil.java
  src/main/java/seedu/mark/storage/JsonAdaptedBookmark.java
  src/main/java/seedu/mark/ui/BookmarkCard.java
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/resources/view/BookmarkListCard.fxml
  src/test/data/JsonSerializableMarkTest/typicalBookmarksMark.json
  src/test/java/seedu/mark/logic/commands/CacheCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/OfflineCommandTest.java
  src/test/java/seedu/mark/logic/parser/CacheCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/OfflineCommandParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/storage/JsonAdaptedBookmarkTest.java
  src/test/java/seedu/mark/storage/JsonSerializableMarkTest.java
  src/test/java/seedu/mark/testutil/BookmarkBuilder.java
  src/test/java/seedu/mark/testutil/TypicalBookmarks.java
Labels: PR: reviewed-approved

#125 Improve autotag
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AutotagCommand.java
  src/main/java/seedu/mark/logic/parser/AutotagCommandParser.java
  src/main/java/seedu/mark/logic/parser/CliSyntax.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/test/java/seedu/mark/logic/parser/AutotagCommandParserTest.java
Labels: PR: reviewed-approved

#138 Implement favorite command
  src/main/java/seedu/mark/logic/commands/FavoriteCommand.java
  src/main/java/seedu/mark/logic/parser/FavoriteCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/ui/BookmarkCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/FavoriteCommandTest.java
  src/test/java/seedu/mark/logic/parser/FavoriteCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#117 Improve URL validation
  src/main/java/seedu/mark/model/bookmark/Url.java
  src/test/java/seedu/mark/model/bookmark/UrlTest.java
Labels: PR: reviewed-approved, type.Enhancement

#139 Fix inconsistencies in UG/DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#133 Support add u/this
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/parser/AddCommandParser.java
  src/main/java/seedu/mark/model/bookmark/Url.java
  src/main/java/seedu/mark/model/bookmark/util/BookmarkBuilder.java
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/java/seedu/mark/ui/BrowserPanel.java
  src/test/java/seedu/mark/logic/LogicManagerTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagCommandTest.java
  src/test/java/seedu/mark/logic/commands/CacheCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
  src/test/java/seedu/mark/logic/commands/OfflineCommandTest.java
  src/test/java/seedu/mark/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/MarkTest.java
  src/test/java/seedu/mark/model/autotag/AutotagControllerTest.java
  src/test/java/seedu/mark/model/autotag/BookmarkTaggerTest.java
  src/test/java/seedu/mark/model/autotag/SelectiveBookmarkTaggerTest.java
  src/test/java/seedu/mark/model/bookmark/BookmarkTest.java
  src/test/java/seedu/mark/model/bookmark/UniqueBookmarkListTest.java
  src/test/java/seedu/mark/model/bookmark/UrlTest.java
  src/test/java/seedu/mark/model/predicates/IdentifiersContainKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/UrlContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/testutil/ReminderBuilder.java
  src/test/java/seedu/mark/testutil/TypicalBookmarks.java
Labels: PR: reviewed-approved

#142 Improve adding folders
  src/main/java/seedu/mark/commons/core/Messages.java
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AddFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
Labels: PR: reviewed-approved

#145 Replace Paths.get() with Path.of()
  src/main/java/seedu/mark/AppParameters.java
  src/main/java/seedu/mark/commons/core/Config.java
  src/main/java/seedu/mark/commons/util/FileUtil.java
  src/main/java/seedu/mark/model/UserPrefs.java
  src/main/java/seedu/mark/ui/StatusBarFooter.java
  src/test/java/seedu/mark/AppParametersTest.java
  src/test/java/seedu/mark/commons/util/ConfigUtilTest.java
  src/test/java/seedu/mark/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/mark/model/ModelManagerTest.java
  src/test/java/seedu/mark/storage/JsonMarkStorageTest.java
  src/test/java/seedu/mark/storage/JsonSerializableMarkTest.java
  src/test/java/seedu/mark/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/mark/testutil/TestUtil.java
Labels: PR: reviewed-approved

#143 Implement find by folder/tag
  src/main/java/seedu/mark/logic/commands/FindCommand.java
  src/main/java/seedu/mark/logic/parser/FindCommandParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/predicates/BookmarkContainsKeywordsPredicate.java
  src/main/java/seedu/mark/model/predicates/FolderContainsKeywordsPredicate.java
  src/main/java/seedu/mark/model/predicates/TagContainsKeywordsPredicate.java
  src/test/java/seedu/mark/logic/commands/FindCommandTest.java
  src/test/java/seedu/mark/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
Labels: PR: reviewed-approved

#146 Only allow caching one copy
  src/main/java/seedu/mark/logic/commands/CacheCommand.java
  src/main/java/seedu/mark/ui/BookmarkCard.java
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/resources/view/BookmarkListCard.fxml
Labels: PR: reviewed-approved

#144 Support opening bookmark from GUI
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/FolderStructureTreeView.java
  src/main/java/seedu/mark/ui/MainWindow.java
Labels: PR: reviewed-approved

#110 Link address bar to embedded browser
  src/main/java/seedu/mark/ui/BrowserPanel.java
  src/main/resources/view/redirectionPage.html
Labels: PR: reviewed-approved, severity.Medium, type.Bug

#150 Add delete cache
  src/main/java/seedu/mark/logic/commands/DeleteCacheCommand.java
  src/main/java/seedu/mark/logic/parser/DeleteCacheCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/test/java/seedu/mark/logic/commands/DeleteCacheCommandTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
Labels: PR: reviewed-approved

#154 Add tests for FindCommand and change folder/tag keyword match to case insensitive
  src/main/java/seedu/mark/model/predicates/FolderContainsKeywordsPredicate.java
  src/main/java/seedu/mark/model/predicates/TagContainsKeywordsPredicate.java
  src/test/java/seedu/mark/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/mark/model/predicates/BookmarkContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/FolderContainsKeywordsPredicateTest.java
  src/test/java/seedu/mark/model/predicates/TagContainsKeywordsPredicateTest.java
Labels: PR: reviewed-approved

#151 Update find, favorite, goto, undo, redo sections for UG
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#148 Support multiple undo/redo
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/logic/parser/RedoCommandParser.java
  src/main/java/seedu/mark/logic/parser/UndoCommandParser.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/VersionedMark.java
  src/test/java/seedu/mark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/mark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/mark/logic/parser/RedoCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/UndoCommandParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#157 Add tests for Goto, Undo, Redo commands and VersionedMark
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/VersionedMark.java
  src/test/java/seedu/mark/logic/commands/EditBookmarkDescriptorTest.java
  src/test/java/seedu/mark/logic/commands/GotoCommandTest.java
  src/test/java/seedu/mark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/mark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/mark/model/MarkStateRecordTest.java
  src/test/java/seedu/mark/model/ModelManagerTest.java
  src/test/java/seedu/mark/model/VersionedMarkTest.java
Labels: PR: reviewed-approved

#141 Implement full autotag command
  docs/UserGuide.adoc
  src/main/java/seedu/mark/commons/util/FileUtil.java
  src/main/java/seedu/mark/logic/commands/AutotagCommand.java
  src/main/java/seedu/mark/logic/commands/AutotagDeleteCommand.java
  src/main/java/seedu/mark/logic/parser/AutotagCommandParser.java
  src/main/java/seedu/mark/logic/parser/AutotagDeleteCommandParser.java
  src/main/java/seedu/mark/logic/parser/CliSyntax.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/main/java/seedu/mark/model/autotag/SelectiveBookmarkTagger.java
  src/main/java/seedu/mark/model/predicates/BookmarkPredicate.java
  src/main/java/seedu/mark/storage/JsonAdaptedAutotagController.java
  src/main/java/seedu/mark/storage/JsonAdaptedBookmark.java
  src/main/java/seedu/mark/storage/JsonAdaptedBookmarkPredicate.java
  src/main/java/seedu/mark/storage/JsonAdaptedSelectiveBookmarkTagger.java
  src/main/java/seedu/mark/storage/JsonAdaptedTag.java
  src/main/java/seedu/mark/storage/JsonSerializableMark.java
  src/test/java/seedu/mark/logic/commands/AddCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagDeleteCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditCommandTest.java
  src/test/java/seedu/mark/logic/parser/AutotagCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/AutotagDeleteCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/autotag/AutotagControllerTest.java
  src/test/java/seedu/mark/model/autotag/SelectiveBookmarkTaggerTest.java
  src/test/java/seedu/mark/model/predicates/BookmarkPredicateTest.java
Labels: PR: reviewed-approved, priority.High

#123 Reminder UI + Storage
  src/main/java/seedu/mark/commons/core/Messages.java
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/logic/commands/AddReminderCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteReminderCommand.java
  src/main/java/seedu/mark/logic/commands/EditReminderCommand.java
  src/main/java/seedu/mark/logic/parser/DeleteReminderCommandParser.java
  src/main/java/seedu/mark/logic/parser/EditReminderCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/logic/parser/ParserUtil.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/ReadOnlyMark.java
  src/main/java/seedu/mark/model/reminder/Reminder.java
  src/main/java/seedu/mark/model/reminder/ReminderAssociation.java
  src/main/java/seedu/mark/storage/JsonAdaptedReminder.java
  src/main/java/seedu/mark/storage/JsonSerializableMark.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/ReminderListPanel.java
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/ReminderList.fxml
  src/test/data/JsonMarkStorageTest/invalidAndValidBookmarkMark.json
  src/test/data/JsonMarkStorageTest/invalidBookmarkMark.json
  src/test/data/JsonSerializableMarkTest/duplicateBookmarkMark.json
  src/test/data/JsonSerializableMarkTest/duplicateFolderInFolderStructureMark.json
  src/test/data/JsonSerializableMarkTest/invalidBookmarkMark.json
  src/test/data/JsonSerializableMarkTest/noRootFolderInStructureMark.json
  src/test/data/JsonSerializableMarkTest/typicalBookmarksMark.json
  src/test/java/seedu/mark/logic/commands/AddReminderCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/DeleteReminderCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditReminderCommandTest.java
  src/test/java/seedu/mark/logic/parser/DeleteReminderCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/EditReminderCommandParserTest.java
  src/test/java/seedu/mark/model/MarkTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/reminder/ReminderAssociationTest.java
  src/test/java/seedu/mark/model/reminder/ReminderTest.java
  src/test/java/seedu/mark/testutil/EditReminderDescriptorBuilder.java
  src/test/java/seedu/mark/testutil/ReminderBuilder.java
  src/test/java/seedu/mark/testutil/TypicalBookmarks.java
  src/test/java/seedu/mark/testutil/TypicalIndexes.java
  src/test/java/seedu/mark/testutil/TypicalReminders.java
Labels: PR: reviewed-approved

#153 Implement expand/collapse and update ug
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/CollapseCommand.java
  src/main/java/seedu/mark/logic/commands/ExpandCommand.java
  src/main/java/seedu/mark/logic/commands/results/CommandResult.java
  src/main/java/seedu/mark/logic/commands/results/ExpandCommandResult.java
  src/main/java/seedu/mark/logic/parser/CollapseCommandParser.java
  src/main/java/seedu/mark/logic/parser/ExpandCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/FolderStructureTreeView.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/test/java/seedu/mark/logic/commands/results/ExpandCommandResultTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
Labels: PR: reviewed-approved

#161 Remove println and update folder docs in ug
  docs/UserGuide.adoc
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
Labels: PR: reviewed-approved

#169 Improve UG and command messages
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AddCommand.java
  src/main/java/seedu/mark/logic/commands/CacheCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteAnnotationCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteCacheCommand.java
  src/main/java/seedu/mark/logic/commands/EditAnnotationCommand.java
  src/main/java/seedu/mark/logic/commands/EditCommand.java
  src/main/java/seedu/mark/logic/commands/FindCommand.java
  src/main/java/seedu/mark/logic/commands/RedoCommand.java
  src/main/java/seedu/mark/logic/commands/UndoCommand.java
Labels: PR: reviewed-approved

#174 Fix annotation to reflect changes for undo/redo
  src/main/java/seedu/mark/logic/commands/AddAnnotationCommand.java
  src/main/java/seedu/mark/logic/parser/AddAnnotationCommandParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/ReadOnlyMark.java
  src/test/java/seedu/mark/model/MarkTest.java
Labels: PR: reviewed-approved, priority.High, type.Bug
