Repository AY1920S1-CS2103T-T13-4/main, pull requests merged in 2019-11, with the labels that each got.

#176 Update annotate examples in user guide
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#175 Show currently active tab and full tab name
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: PR: reviewed-approved

#221 Minor re-formatting of DevGuide appendices
  docs/DeveloperGuide.adoc
Labels: PR: reviewed-approved, documentation

#224 Fix noargument commands
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/logic/parser/ParserUtil.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/logic/parser/ParserUtilTest.java
Labels: PR: reviewed-approved

#226 Validate file names for Import and Export
  docs/UserGuide.adoc
  src/main/java/seedu/mark/commons/core/Messages.java
  src/main/java/seedu/mark/logic/parser/ExportCommandParser.java
  src/main/java/seedu/mark/logic/parser/ImportCommandParser.java
  src/main/java/seedu/mark/logic/parser/ParserUtil.java
  src/test/java/seedu/mark/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/ImportCommandParserTest.java
Labels: PR: reviewed-approved

#223 Fix folders
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/storage/JsonAdaptedFolderStructure.java
  src/main/java/seedu/mark/storage/JsonSerializableMark.java
  src/test/data/JsonSerializableMarkTest/nonexistentFolderInBookmark.json
  src/test/java/seedu/mark/storage/JsonSerializableMarkTest.java
Labels: PR: reviewed-approved

#230 fix dry test bugs
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AddReminderCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteReminderCommand.java
  src/main/java/seedu/mark/logic/commands/EditReminderCommand.java
  src/main/java/seedu/mark/logic/parser/ParserUtil.java
  src/main/java/seedu/mark/model/reminder/Reminder.java
  src/main/java/seedu/mark/storage/JsonAdaptedReminder.java
  src/test/java/seedu/mark/testutil/ReminderBuilder.java
Labels: PR: unreviewed

#227 Update SampleDataUtil (basic, autotag, reminder)
  src/main/java/seedu/mark/model/util/SampleDataUtil.java
  src/test/java/seedu/mark/model/util/SampleDataUtilTest.java
Labels: PR: reviewed-approved

#234 Add portfolio page (Nazhou)
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/na-nazhou.adoc
Labels: PR: reviewed-approved

#232 Add favorite bookmarks to dashboard
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/logic/commands/FavoriteCommand.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/bookmark/Bookmark.java
  src/main/java/seedu/mark/model/tag/Tag.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/java/seedu/mark/ui/FavoriteListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/FavoriteListPanel.fxml
  src/main/resources/view/FolderStructure.fxml
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#233 Add portfolio page (Dorcas)
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/dorcastan.adoc
Labels: PR: reviewed-approved

#237 Add PPP (daryl)
  docs/AboutUs.adoc
  docs/team/daryl-tan.adoc
Labels: PR: reviewed-approved

#236 hsiaohan ppp
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/Hsiao-Han.adoc
Labels: PR: reviewed-approved

#231 Add autotag display to dashboard and fix bugs
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/ReadOnlyMark.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/main/java/seedu/mark/model/predicates/BookmarkPredicate.java
  src/main/java/seedu/mark/model/util/SampleDataUtil.java
  src/main/java/seedu/mark/storage/JsonAdaptedAutotagController.java
  src/main/java/seedu/mark/storage/JsonAdaptedBookmarkPredicate.java
  src/main/java/seedu/mark/storage/JsonAdaptedSelectiveBookmarkTagger.java
  src/main/java/seedu/mark/ui/AutotagTablePanel.java
  src/main/java/seedu/mark/ui/DashboardPanel.java
  src/main/resources/view/AutotagTablePanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
  src/test/java/seedu/mark/model/MarkTest.java
  src/test/java/seedu/mark/model/autotag/AutotagControllerTest.java
  src/test/java/seedu/mark/model/predicates/BookmarkPredicateTest.java
  src/test/java/seedu/mark/storage/JsonAdaptedBookmarkPredicateTest.java
Labels: PR: reviewed-approved

#238 Create ppp file
  docs/team/kxyoke.adoc
Labels: PR: reviewed-approved

#246 New look for our UI!
  src/main/java/seedu/mark/logic/commands/DeleteCacheCommand.java
  src/main/java/seedu/mark/logic/commands/OfflineCommand.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/annotation/OfflineDocument.java
  src/main/java/seedu/mark/ui/AnnotationParagraphCard.java
  src/main/java/seedu/mark/ui/BookmarkCard.java
  src/main/java/seedu/mark/ui/BookmarkListPanel.java
  src/main/java/seedu/mark/ui/FolderStructureTreeView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/FavoriteListPanel.fxml
  src/main/resources/view/FolderStructure.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OfflinePanel.fxml
  src/main/resources/view/textBkgrd.css
  src/test/java/seedu/mark/logic/commands/DeleteCacheCommandTest.java
  src/test/java/seedu/mark/logic/commands/OfflineCommandTest.java
Labels: PR: reviewed-approved

#250 Fix bugs
  src/main/java/seedu/mark/logic/parser/TabCommandParser.java
  src/main/resources/view/AnnotationListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/OfflinePanel.fxml
Labels: PR: reviewed-approved

#252 Improve folder ui
  src/main/resources/view/BookmarkListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
Labels: PR: reviewed-approved

#249 Update User guide to mark out areas that need screenshots
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/parser/ParserUtil.java
  src/main/java/seedu/mark/model/annotation/ParagraphIdentifier.java
  src/test/java/seedu/mark/logic/parser/AddAnnotationCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/DeleteAnnotationCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/ParserUtilTest.java
  src/test/java/seedu/mark/model/annotation/ParagraphIdentifierTest.java
Labels: PR: reviewed-approved

#248 Reformat User Guide
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#251 Goto reminder command
  src/main/java/seedu/mark/logic/commands/GotoReminderCommand.java
  src/main/java/seedu/mark/logic/parser/GotoReminderCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/reminder/ReminderAssociation.java
  src/test/java/seedu/mark/logic/commands/GotoReminderCommandTest.java
  src/test/java/seedu/mark/logic/parser/GotoReminderCommandParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
Labels: PR: reviewed-approved

#253 Update browser address parsing to just load about:blank
  src/main/java/seedu/mark/ui/BrowserPanel.java
Labels: PR: reviewed-approved, help wanted

#228 Reminder Notification
  build.gradle
  src/main/java/seedu/mark/logic/Logic.java
  src/main/java/seedu/mark/logic/LogicManager.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/reminder/Reminder.java
  src/main/java/seedu/mark/ui/MainWindow.java
  src/main/java/seedu/mark/ui/ReminderListPanel.java
  src/main/resources/images/bell 2.png
  src/main/resources/images/bell.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/ReminderList.fxml
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/model/MarkTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/testutil/TypicalReminders.java
Labels: PR: reviewed-approved

#256 Standardise the styles of favorites panel
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardPanel.fxml
  src/main/resources/view/FavoriteListPanel.fxml
  src/main/resources/view/FolderStructure.fxml
Labels: PR: reviewed-approved

#254 Update documentation — UG Autotags and DG design of Model
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AnnotationPackageClassDiagram.puml
  docs/diagrams/AutotagPackageClassDiagram.puml
  docs/diagrams/BookmarkPackageClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReminderPackageClassDiagram.puml
  docs/images/AnnotationPackageClassDiagram.png
  docs/images/AutotagPackageClassDiagram.png
  docs/images/BookmarkPackageClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ReminderPackageClassDiagram.png
  docs/images/ui-screenshots/AddCommandExample1.png
  docs/team/dorcastan.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/mark/model/Mark.java
Labels: PR: reviewed-approved

#255 Add folder-edit, folder-delete
  docs/UserGuide.adoc
  src/main/java/seedu/mark/commons/core/Messages.java
  src/main/java/seedu/mark/logic/commands/AddFolderCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteFolderCommand.java
  src/main/java/seedu/mark/logic/commands/EditFolderCommand.java
  src/main/java/seedu/mark/logic/parser/CliSyntax.java
  src/main/java/seedu/mark/logic/parser/DeleteFolderCommandParser.java
  src/main/java/seedu/mark/logic/parser/EditFolderCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/bookmark/Folder.java
  src/main/java/seedu/mark/model/folderstructure/FolderStructure.java
  src/test/java/seedu/mark/logic/commands/AddFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/mark/logic/commands/DeleteFolderCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditFolderCommandTest.java
  src/test/java/seedu/mark/logic/parser/DeleteFolderCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/EditFolderCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/MarkParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/bookmark/FolderTest.java
  src/test/java/seedu/mark/model/folderstructure/FolderStructureTest.java
Labels: PR: reviewed-approved

#258 Add autotag-edit
  docs/UserGuide.adoc
  src/main/java/seedu/mark/logic/commands/AutotagDeleteCommand.java
  src/main/java/seedu/mark/logic/commands/EditAutotagCommand.java
  src/main/java/seedu/mark/logic/parser/AutotagCommandParser.java
  src/main/java/seedu/mark/logic/parser/EditAutotagCommandParser.java
  src/main/java/seedu/mark/logic/parser/MarkParser.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/Model.java
  src/main/java/seedu/mark/model/ModelManager.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/main/java/seedu/mark/model/autotag/SelectiveBookmarkTagger.java
  src/test/java/seedu/mark/logic/commands/AutotagCommandTest.java
  src/test/java/seedu/mark/logic/commands/AutotagDeleteCommandTest.java
  src/test/java/seedu/mark/logic/commands/EditAutotagCommandTest.java
  src/test/java/seedu/mark/logic/parser/AutotagCommandParserTest.java
  src/test/java/seedu/mark/logic/parser/EditAutotagCommandParserTest.java
  src/test/java/seedu/mark/model/ModelStub.java
  src/test/java/seedu/mark/model/autotag/AutotagControllerTest.java
  src/test/java/seedu/mark/model/autotag/SelectiveBookmarkTaggerTest.java
  src/test/java/seedu/mark/testutil/TypicalBookmarks.java
Labels: PR: reviewed-approved

#260 Add ppp, manual testing instructions and edit ug dg
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MarkStateRecordClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/MarkStateRecordClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/team/na-nazhou.adoc
Labels: PR: reviewed-approved

#259 Update developers guide - annotation feature and model's annotation
  AnnotationSequenceDiagram.png
  docs/DeveloperGuide.adoc
  docs/diagrams/AddAnnotationSequenceDiagram.puml
  docs/diagrams/AnnotationActivityDiagram.puml
  docs/diagrams/AnnotationCommandStructure.puml
  docs/diagrams/AnnotationPackageClassDiagram.puml
  docs/diagrams/AnnotationSequenceDiagram.puml
  docs/diagrams/DeleteAnnotationSequenceDiagram.puml
  docs/diagrams/EditAnnotationSequenceDiagram.puml
  docs/images/AddAnnotationSequenceDiagram.png
  docs/images/AnnotationActivityDiagram.png
  docs/images/AnnotationCommandStructure.png
  docs/images/AnnotationPackageClassDiagram.png
  docs/images/AnnotationSequenceDiagram.png
  docs/images/DeleteAnnotationSequenceDiagram.png
  docs/images/EditAnnotationSequenceDiagram.png
  src/main/java/seedu/mark/logic/commands/AddAnnotationCommand.java
  src/main/java/seedu/mark/logic/commands/AnnotationCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteAnnotationAllCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteAnnotationHighlightCommand.java
  src/main/java/seedu/mark/logic/commands/DeleteAnnotationNoteCommand.java
  src/main/java/seedu/mark/logic/commands/EditAnnotationCommand.java
Labels: PR: reviewed-approved

#261 Add PPP(Daryl) update ug and dg for folders
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/daryl-tan.adoc
  docs/team/openorclose.adoc
  src/main/java/seedu/mark/ui/FolderStructureTreeView.java
Labels: PR: reviewed-approved

#262 update ppp
  docs/team/openorclose.adoc
Labels: PR: reviewed-approved

#257 Edit UG, DG, PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddReminderSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ReminderActivityDiagram.puml
  docs/images/AddReminderSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ReminderActivityDiagram.png
  docs/images/ReminderAssociationDiagram.png
  docs/images/ui-screenshots/AddReminderUi1.png
  docs/images/ui-screenshots/AddReminderUi2.png
  docs/images/ui-screenshots/AddReminderUi3.png
  docs/images/ui-screenshots/AddReminderUi4.png
  docs/images/ui-screenshots/DeleteReminderUi1.png
  docs/images/ui-screenshots/DeleteReminderUi2.png
  docs/images/ui-screenshots/DeleteReminderUi3.png
  docs/images/ui-screenshots/EditReminderUi1.png
  docs/images/ui-screenshots/EditReminderUi2.png
  docs/images/ui-screenshots/EditReminderUi3.png
  docs/images/ui-screenshots/EditReminderUi4.png
  docs/images/ui-screenshots/GotoReminderUi1.png
  docs/images/ui-screenshots/GotoReminderUi2.png
  docs/images/ui-screenshots/GotoReminderUi3.png
  docs/team/Hsiao-Han.adoc
  docs/team/TSAI-HSIAO-HAN.adoc
  src/main/java/seedu/mark/logic/commands/GotoReminderCommand.java
Labels: PR: reviewed-approved

#265 update ppp again
  docs/UserGuide.adoc
  docs/team/openorclose.adoc
Labels: PR: reviewed-approved

#263 Fix ppp(Nazhou)
  docs/DeveloperGuide.adoc
  docs/team/na-nazhou.adoc
Labels: PR: reviewed-approved

#267 update dg storage component
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: PR: reviewed-approved

#264 Update Developer Guide (Model component and Autotag implementation)
  docs/DeveloperGuide.adoc
  docs/diagrams/AnnotationPackageClassDiagram.puml
  docs/diagrams/ApplyAllTaggersSequenceDiagram.puml
  docs/diagrams/AutotagPackageClassDiagram.puml
  docs/diagrams/AutotagSequenceDiagram.puml
  docs/diagrams/AutotagState0.puml
  docs/diagrams/AutotagState1.puml
  docs/diagrams/AutotagState2.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AnnotationPackageClassDiagram.png
  docs/images/ApplyAllTaggersSequenceDiagram.png
  docs/images/AutotagPackageClassDiagram.png
  docs/images/AutotagSequenceDiagram.png
  docs/images/AutotagState0.png
  docs/images/AutotagState1.png
  docs/images/AutotagState2.png
  docs/images/ModelClassDiagram.png
  docs/team/dorcastan.adoc
Labels: PR: reviewed-approved

#266 Edit ppp
  docs/team/TSAI-HSIAO-HAN.adoc
Labels: PR: reviewed-approved

#268 Add testing instructions (autotags, export, import) + Fix autotag & import bugs
  docs/DeveloperGuide.adoc
  src/main/java/seedu/mark/logic/commands/ImportCommand.java
  src/main/java/seedu/mark/model/Mark.java
  src/main/java/seedu/mark/model/autotag/AutotagController.java
  src/test/java/seedu/mark/logic/commands/ImportCommandTest.java
  src/test/java/seedu/mark/storage/StorageStub.java
Labels: PR: reviewed-approved

#270 update ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/openorclose.adoc
Labels: PR: reviewed-approved

#272 Update: Autotag implementation in DevGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AutotagPackageClassDiagram.png
  docs/team/dorcastan.adoc
Labels: PR: reviewed-approved

#275 Update images for User guide
  docs/UserGuide.adoc
  docs/images/ui-screenshots/AddAnnotationCommandUi1.png
  docs/images/ui-screenshots/AddAnnotationCommandUi2.png
  docs/images/ui-screenshots/AddReminderUi1.png
  docs/images/ui-screenshots/AddReminderUi2.png
  docs/images/ui-screenshots/AddReminderUi3.png
  docs/images/ui-screenshots/AddReminderUi4.png
  docs/images/ui-screenshots/AutotagCommandExample1.png
  docs/images/ui-screenshots/AutotagCommandExample2.png
  docs/images/ui-screenshots/AutotagCommandUi1.png
  docs/images/ui-screenshots/AutotagCommandUi2.png
  docs/images/ui-screenshots/AutotagDeleteCommandUi1.png
  docs/images/ui-screenshots/AutotagDeleteCommandUi2.png
  docs/images/ui-screenshots/AutotagEditComandExample2.png
  docs/images/ui-screenshots/AutotagEditCommandExample1.png
  docs/images/ui-screenshots/AutotagEditCommandUi1.png
  docs/images/ui-screenshots/AutotagEditCommandUi2.png
  docs/images/ui-screenshots/CacheCommandUi1.png
  docs/images/ui-screenshots/CacheCommandUi2.png
  docs/images/ui-screenshots/DeleteAnnotationCommandUi1.png
  docs/images/ui-screenshots/DeleteAnnotationCommandUi2.png
  docs/images/ui-screenshots/DeleteReminderUi1.png
  docs/images/ui-screenshots/DeleteReminderUi2.png
  docs/images/ui-screenshots/EditAnnotationCommandUi1.png
  docs/images/ui-screenshots/EditAnnotationCommandUi2.png
  docs/images/ui-screenshots/EditReminderUi1.png
  docs/images/ui-screenshots/EditReminderUi2.png
  docs/images/ui-screenshots/GotoReminderUi1.png
  docs/images/ui-screenshots/GotoReminderUi2.png
Labels: PR: reviewed-approved

#274 Update images
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/ui-screenshots/AddCommandUi1.png
  docs/images/ui-screenshots/AddCommandUi2.png
  docs/images/ui-screenshots/AddFolderCommandUi1.png
  docs/images/ui-screenshots/AddFolderCommandUi2.png
  docs/images/ui-screenshots/BookmarkList.png
  docs/images/ui-screenshots/ClearCommandUi1.png
  docs/images/ui-screenshots/ClearCommandUi2.png
  docs/images/ui-screenshots/CollapseCommandUi1.png
  docs/images/ui-screenshots/CollapseCommandUi2.png
  docs/images/ui-screenshots/CommandBox.png
  docs/images/ui-screenshots/DeleteCommandUI1.png
  docs/images/ui-screenshots/DeleteCommandUI2.png
  docs/images/ui-screenshots/DeleteFolderCommandUi1.png
  docs/images/ui-screenshots/DeleteFolderCommandUi2.png
  docs/images/ui-screenshots/EditCommandUI1.png
  docs/images/ui-screenshots/EditCommandUI2.png
  docs/images/ui-screenshots/EditFolderCommandUi1.png
  docs/images/ui-screenshots/EditFolderCommandUi2.png
  docs/images/ui-screenshots/ExpandCommandUi1.png
  docs/images/ui-screenshots/ExpandCommandUi2.png
  docs/images/ui-screenshots/FindCommandUI1.png
  docs/images/ui-screenshots/FindCommandUI2.png
  docs/images/ui-screenshots/FolderHierarchy.png
  docs/images/ui-screenshots/TabUI1.png
  docs/images/ui-screenshots/TabUI2.png
  docs/images/ui-screenshots/Ui_OfflineTab.png
  docs/images/ui-screenshots/Ui_OnlineTab.png
Labels: PR: reviewed-approved

#271 edit ppp
  docs/team/TSAI-HSIAO-HAN.adoc
Labels: PR: reviewed-approved

#278 Fix sequence diagram
  docs/diagrams/FolderSequenceDiagram.puml
  docs/images/FolderSequenceDiagram.png
Labels: PR: reviewed-approved

#277 Add ui screenshots for favorite command
  docs/UserGuide.adoc
  docs/images/ui-screenshots/FavoriteCommandUI1.png
  docs/team/na-nazhou.adoc
Labels: PR: reviewed-approved

#279 Rename images
  README.adoc
  docs/UserGuide.adoc
  docs/images/ui-screenshots/DeleteCommandUi1.png
  docs/images/ui-screenshots/DeleteCommandUi2.png
  docs/images/ui-screenshots/EditCommandUi1.png
  docs/images/ui-screenshots/EditCommandUi2.png
  docs/images/ui-screenshots/FindCommandUi1.png
  docs/images/ui-screenshots/FindCommandUi2.png
  docs/images/ui-screenshots/TabUi1.png
  docs/images/ui-screenshots/TabUi2.png
Labels: PR: reviewed-approved

#280 Fix images
  docs/images/ui-screenshots/AddCommandExample1.png
  docs/images/ui-screenshots/AddCommandExample2.png
  docs/images/ui-screenshots/AutotagPanel.png
Labels: PR: reviewed-approved

#282 Fix more images
  docs/images/ui-screenshots/DeleteReminderUi3.png
  docs/images/ui-screenshots/EditReminderUi3.png
Labels: PR: reviewed-approved

#281 Fix ui.png in readme
  README.adoc
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#284 Hi
  docs/UserGuide.adoc
  docs/images/ui-screenshots/AddFolderCommandUi2.png
  docs/images/ui-screenshots/AddReminderUi1.png
  docs/images/ui-screenshots/AddReminderUi2.png
  docs/images/ui-screenshots/AddReminderUi3.png
  docs/images/ui-screenshots/DeleteReminderUi1.png
  docs/images/ui-screenshots/DeleteReminderUi2.png
  docs/images/ui-screenshots/DeleteReminderUi3.png
  docs/images/ui-screenshots/EditFolderCommandUi1.png
  docs/images/ui-screenshots/EditFolderCommandUi2.png
  docs/images/ui-screenshots/EditReminderUi1.png
  docs/images/ui-screenshots/EditReminderUi2.png
  docs/images/ui-screenshots/EditReminderUi3.png
Labels: PR: reviewed-approved

#276 Update PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AutotagState0.puml
  docs/diagrams/AutotagState1.puml
  docs/diagrams/AutotagState2.puml
  docs/images/AutotagState0.png
  docs/images/AutotagState1.png
  docs/images/AutotagState2.png
  docs/images/ui-screenshots/AutotagCommandExample1.png
  docs/images/ui-screenshots/AutotagCommandExample2.png
  docs/images/ui-screenshots/AutotagCommandUi1.png
  docs/images/ui-screenshots/AutotagCommandUi2.png
  docs/images/ui-screenshots/AutotagDeleteCommandUi1.png
  docs/images/ui-screenshots/AutotagDeleteCommandUi2.png
  docs/images/ui-screenshots/AutotagEditCommandExample1.png
  docs/images/ui-screenshots/AutotagEditCommandExample2.png
  docs/images/ui-screenshots/AutotagEditCommandUi1.png
  docs/images/ui-screenshots/AutotagEditCommandUi2.png
  docs/images/ui-screenshots/AutotagPanel.png
  docs/images/ui-screenshots/ExportCommandUi1.png
  docs/images/ui-screenshots/ExportCommandUi2.png
  docs/images/ui-screenshots/ImportCommandUi0.png
  docs/images/ui-screenshots/ImportCommandUi1.png
  docs/images/ui-screenshots/ImportCommandUi2.png
  docs/team/dorcastan.adoc
Labels: PR: reviewed-approved

#269 Update ppp to fit within 10 pages
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/dashboardMark.png
  docs/images/ui-screenshots/AddAnnotationCommandUi1.png
  docs/images/ui-screenshots/AddAnnotationCommandUi2.png
  docs/images/ui-screenshots/AddAnnotationCommandUiCmd.png
  docs/images/ui-screenshots/AddAnnotationCommandUiRes2.png
  docs/images/ui-screenshots/DeleteAnnotationCommandUi1.png
  docs/images/ui-screenshots/DeleteAnnotationCommandUi2.png
  docs/images/ui-screenshots/EditAnnotationCommandUi1.png
  docs/images/ui-screenshots/EditAnnotationCommandUi1before.png
  docs/images/ui-screenshots/EditAnnotationCommandUi2.png
  docs/images/ui-screenshots/EditAnnotationCommandUi2after.png
  docs/stylesheets/gh-pages.css
  docs/team/kxyoke.adoc
Labels: PR: reviewed-approved

#285 Tiny change to PPP
  docs/team/dorcastan.adoc
Labels: PR: reviewed-approved

#286 Highlight
  docs/UserGuide.adoc
  docs/images/ui-screenshots/AddReminderUi1.png
  docs/images/ui-screenshots/AddReminderUi2.png
  docs/images/ui-screenshots/AddReminderUi4.png
  docs/images/ui-screenshots/DeleteReminderUi1.png
  docs/images/ui-screenshots/DeleteReminderUi2.png
  docs/images/ui-screenshots/EditReminderUi1.png
  docs/images/ui-screenshots/EditReminderUi2.png
  docs/images/ui-screenshots/EditReminderUi4.png
  docs/images/ui-screenshots/GotoReminderUi1.png
  docs/images/ui-screenshots/GotoReminderUi2.png
Labels: PR: reviewed-approved

#287 fix
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#288 Fix: Typos and missing testing instructions
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: PR: reviewed-approved

#289 ug
  docs/UserGuide.adoc
  docs/team/TSAI-HSIAO-HAN.adoc
Labels: PR: reviewed-approved
